### ISSUE TITLE
Normalization of CODEX data

### ISSUE THREAD

**Issue by leobalzano** [CamaraLab/STvEA#17]
Hello. I don't understand how you normalize the CODEX data in your article.
You mentioned the following:
We normalized the processed CODEX data by the total levels in each cell
where Mhi is the level of antigen h in cell i before normalization. After this process, antigen levels are well approximated by a two- component Gaussian mixture model where the Gaussian with the highest median corresponds to the sig- nal component, and the mixing parameter ah represents the proba- bility of a measurement of antigen h actually coming from the background. Upon fitting the model to the data using the expectation- maximization algorithm for maximum likelihood estimation, we filtered out the background component of the data by considering
the probabilities"

Could you please tell me where is the code to perform this normalization.
Thanks a lot
Leandro Balzano

**Comment by govekk** [comment]
The [CleanCODEX()](https://github.com/CamaraLab/STvEA/blob/94da20296e9a1d9be97de7d658839ae345f886f4/R/data_processing.R#L52-L109) function performs both parts of this normalization: first, it divides each CODEX value by the total expression per cell, then fits a two component Gaussian mixture model and takes the new normalized expression as the value of the CDF of the higher Gaussian component at each expression value.
