### ISSUE TITLE
Error during MapCODEXtoCITE()

### ISSUE THREAD

**Issue by aanchalsharma833** [CamaraLab/STvEA#20]
Hi,

I'm interested in using STvEA for integrating CODEX data with CITEseq data, but got stuck at MapCODEXtoCITE call with following error:

```
stvea_object <- MapCODEXtoCITE(stvea_object, num_chunks=8, seed=30, num_cores=20)
Error in (nrow(cite_protein) + 1):nrow(corrected_data[[i]]) : 
  argument of length 0
In addition: Warning message:
In mclapply(1:length(chunk_ids), function(i) AnchorCorrection(ref_mat = cite_protein,  :
  all scheduled cores encountered errors in user code

```

I tried running it step by step as  #[mentioned](https://github.com/CamaraLab/STvEA/issues/19)  and found that it is getting stuck at following call:

```
scoredAnchors <- ScoreAnchors(neighbors, filteredAnchors, nrow(ref_mat), nrow(query_mat), k.score=k.score, verbose=verbose)
Scoring anchors
Error in sparseMatrix(i = i, j = j, x = 1, dims = dims) : 
  all(dims >= dims.min) is not TRUE
In addition: Warning message:
In ScoreAnchors(neighbors, filteredAnchors, nrow(ref_mat), nrow(query_mat),  :
  Requested k.score = 80, only 50 in dataset
```

I looked for NAs in dataset - none found. Could anyone please guide as to what could be causing this?

**Comment by aanchalsharma833** [comment]
Thanks for your reply. But I could resolve the issue. The problem was in sectioning/subsetting the codex data. There were very few cells upon subsetting. I changed the parameters to include more cells.

Although there is another issue I am facing in plotting the Cite seq data.

```
ggplot(stvea_object@cite_emb, aes_string(x = colnames(stvea_object@cite_emb)[1],  y = colnames(stvea_object@cite_emb)[2], color = factor(1:length(color)))) + geom_point(size = pt_size) + labs(title = paste(print_type,  "expression"), subtitle = subtitle) + scale_color_manual(values = alpha(color,  1), guide = FALSE) + theme_void()
Error: Aesthetics must be either length 1 or the same as the data (1310): colour
Run `rlang::last_error()` to see where the error occurred.
```

I tried removing ```color = factor(1:length(color))``` and plot it. It gives me the plot but without colors. Example plots appear fine. Any clue what is happening?

Also, another error:

```
cite_cluster_adj <- AdjScoreClustersCITE(stvea_object, k=3, num_cores=8)
Error in cluster_matrix %*% t(transfer_matrix) : 
  Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 88

```

Any insight is appreciated.

**Comment by govekk** [comment]
That makes sense. Sorry for the delay in getting back to this.

**Comment by aanchalsharma833** [comment]
Thanks for pointing out. The dimensions of my latent space data and mRNA data were different. Getting latent space data for same no.of cells as mRNA solved the issue.

Another error I am facing is in GetUmapCODEX() call:

```
>stvea_object <- GetUmapCODEX(stvea_object, metric = 'pearson', n_neighbors=30, min_dist=0.1, negative_sample_rate = 50)
Error in if (abs(val - target) < tolerance) { : 
  missing value where TRUE/FALSE needed

>traceback()
5: smooth.knn.dist(knn$distance, nk, local.connectivity = connectivity, 
       bandwidth = bandwidth)
4: naive.fuzzy.simplicial.set(knn, config)
3: implementations[[method]](d, config)
2: umap::umap(stvea_object@codex_clean, ...)
1: GetUmapCODEX(stvea_object, metric = "pearson", n_neighbors = 30, 
       min_dist = 0.1, negative_sample_rate = 50)
```

Any suggestions would be appreciated.

**Comment by aanchalsharma833** [comment]
Solved the above mentioned error. 
It was caused due to the wrong codex_size information being loaded. It seems the codex_size variable is defined as we load the STvEA library. And the default variable is used in case we are not defining the codex_size variable by reading the size file. Probably a potential bug to be resolved in future updates.
