### ISSUE TITLE
How to map the UMAP result into CODEX spatial figure ?

### ISSUE THREAD

**Issue by bugie19** [CamaraLab/STvEA#21]
Hallo,

This is very excellent tool!.

I have tried the code provided in the section of "Analyzing CODEX data" and it looks working well to my own CODEX dataset. However, I have an obstacle on mapping back the UMAP result into CODEX spatial figure using this code:

PlotExprCODEXspatial(stvea_object, c("marker"))

is there any code must be inputted before I execute that code ? 

your help, I really appreciate in advance.

Best regards,

Bugie

Institute of Biomedical Science, Academia Sinica, Taiwan

**Comment by govekk** [comment]
Hi, I'm glad the CODEX processing is working well for you.

Can you clarify what you mean when you say you have an obstacle running that function? Do you get an error? If so, please include the full error here. 

The main problem that comes to mind, if you are getting the error "stvea_object does not contain CODEX spatial information", is that you must provide the function with spatial X,Y,Z coordinates of each cell from the CODEX images, in the same order as the CODEX protein expression matrices you provided. This must be a (num_cells x 3) matrix.

If the function is successfully plotting, but the image doesn't look correct, your X,Y,Z values might be relative to the image tiles and not the global image. Our ReadDataFCS() function has some ability to convert tile-relative coordinates to global coordinates, based on a few different FCS formats I've seen, but I can't guarantee that it works universally.

If neither of those are your problem, then I would need more information to give advice.
