### ISSUE TITLE
Color legend to interpret the colors in the heatmap (CODEX protein adj map & cluster adj map)

### ISSUE THREAD

**Issue by burcu-ayoglu** [CamaraLab/STvEA#22]
Hi,

Thank you for developing this tool, I'm trying to use it for CODEX data but I find it quite hard to interpret the heatmaps at the moment. And is there a way to play around with the color scheme, as I have difficulty to distinguish what is significant and what not. And is there a way to add a color legend to these heatmaps? 

Thank you,

<img width="646" alt="Screen Shot 2022-04-08 at 09 02 33" src="https://user-images.githubusercontent.com/36070978/162382189-abb7535f-427a-4df3-9008-d44c6e6d987c.png">

**Comment by pcamara** [comment]
Hi,

Thank you for the suggestion. We have updated the function AdjScoreHeatmap() to allow for more control from the user on the color scale and plotting. We hope you will find it helpful.

Pablo
